# Generated by Django 4.1.4 on 2023-01-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMovies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_movies',
            name='img',
            field=models.ImageField(default='dummy_image', upload_to='images'),
            preserve_default=False,
        ),
    ]
